# -*- coding: utf-8 -*-
"""Priority Scheduling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kFeNu3L2DcMl80eli_n_oE35KJ7eZyuV
"""

n = int(input("Enter number of processes: "))

processes = []
for i in range(n):
    pid = "P" + str(i+1)
    at = int(input(f"Arrival Time of {pid}: "))
    bt = int(input(f"Burst Time of {pid}: "))
    pr = int(input(f"Priority of {pid} (small = high priority): "))
    processes.append([pid, at, bt, pr])

time = 0
results = {}

while len(processes) > 0:
    ready = []
    for p in processes:
        if p[1] <= time:
            ready.append(p)

    if len(ready) > 0:

        high = ready[0]
        for p in ready:
            if p[3] < high[3]:
                high = p

        time += high[2]
        ct = time
        tat = ct - high[1]
        wt = tat - high[2]
        results[high[0]] = [high[0], high[1], high[2], high[3], ct, tat, wt]
        processes.remove(high)

    else:
        time += 1

print("\nPID\tAT\tBT\tPR\tCT\tTAT\tWT")
for i in range(1, n+1):
    p = results["P" + str(i)]
    print(f"{p[0]}\t{p[1]}\t{p[2]}\t{p[3]}\t{p[4]}\t{p[5]}\t{p[6]}")